### ISSUE TITLE
Great !!!

### ISSUE THREAD

**Issue by badpenguin** [mdo/table-grid#10]
Great! A full complete grid with just a few line of css.

However you must be clean in the example that you have only 2 possibile use:

a) the template: 1, 1, 1, 1, 1 on mobile (600px)
b) the grid on large then 600px

using table i don't think you can have different breakpoints at custom size, isn't it?

**Comment by mdo** [comment]
Yeah, right now you can't, but additional grid tiers can be added.

**Comment by ajusa** [comment]
Apologies for digging this up 10 years later, but the original comment is correct. With display table, you can either lay out items in a single row, or (as this project does) disable the table when you want to collapse to a single column for mobile devices.

It is not possible to "wrap" table-cells into multiple rows.
