### ISSUE TITLE
"Tables are super impractical for grids ...

### ISSUE THREAD

**Issue by cerebrl** [mdo/table-grid#6]
> "Tables are super impractical for grids because there is no perf gain when using `table-layout: fixed;`, a property that tells the browser to only scrape a table's first row of cells to determine every cell's width for super fast rendering." – [css-perf](https://github.com/mdo/css-perf#grid-techniques)

I'm wondering why you say they're "super impractical", yet you have this project here. I've been using CSS tables for layout for years, and I haven't found them to be bad at all. Could you explain you reasoning?

**Comment by mdo** [comment]
The CSS perf stuff was a one-off set of experiments that ultimately didn't prove too much. That doesn't stop me from experimenting elsewhere with this project though :). They work just fine, but they're not _meant_ for layout, component structure, etc. Still, we can do it, and this shows one of those ways.
