### ISSUE TITLE
Hm.. Grid system?! Really? What we have to do with this wrong vertical gap?

### ISSUE THREAD

**Issue by Dymskiy** [mdo/table-grid#8]
![wtf](https://cloud.githubusercontent.com/assets/7261034/5697549/022d1400-9a05-11e4-8839-ac544d7088aa.png)

**Comment by mdo** [comment]
> Hm.. Grid system?! Really?

Read the readme, please :).

> What we have to do with this wrong vertical gap?

OS, browser, and version?

**Comment by Dymskiy** [comment]
> Read the readme, please :).

Which part? "which adds gutters with `border-spacing: 1rem 0;`. Sucks, but this _is_ an experiment."

> OS, browser, and version?

Same crap (exectly same) at all OSes and all browsers it seems.. (
(Win8, MAC OS X 10.7.5, iOS 4.2, Android 4.1 Chrome34 and mobile Chrome, Safari 6.1, Firefox23, Opera12, IE10 at least)

**Comment by Dymskiy** [comment]
I like your Grid so much (my own was based on float) i was happy for a 5 hours))), but ... my example (
![3452345](https://cloud.githubusercontent.com/assets/7261034/5701299/2a730b18-9a5a-11e4-9728-f5aa5e872350.png)

**Comment by mdo** [comment]
Best guess is it's just how the table rounding is kicking in. Sizing with tables is notoriously weird and inconsistent. If you need pixel perfect control, this probably isn't the grid system/experiment for you :).
