### ISSUE TITLE
Scss support

### ISSUE THREAD

**Issue by Prestapro** [mdo/table-grid#9]
Hi, I'm a little experimenting with display: table
And it's really cool stuff that lets you do a lot of interesting things.
I think of in order to make a complete analog bootstrap grid on scss and then the other preprocessor I think it should be very interesting.
How do you like the idea?

**Comment by mdo** [comment]
Hey there! I don't plan on adding any Sass support here. It's a slightly older project that's just not anywhere near the top of my list of projects to actively maintain right now. Sorry! <3
